<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>TradingService.Infrastructure</RootNamespace>
		<AssemblyName>TradingService.Infrastructure</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TradingService.Application\TradingService.Application.csproj" />
	  <ProjectReference Include="..\TradingService.Domain\TradingService.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="GrpcClients\" />
	  <Folder Include="HttpClients\" />
	  <Folder Include="Messaging\" />
	  <Folder Include="Persistence\" />
	  <Folder Include="Repositories\" />
	  <Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="SharedLibrary">
	    <HintPath>..\..\References\SharedLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Google.Protobuf" Version="3.34.1" />
	  <PackageReference Include="Grpc.Net.ClientFactory" Version="2.80.0" />
	  <PackageReference Include="Grpc.Tools" Version="2.80.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Protobuf Include="Protos\matching_engine.proto" GrpcServices="Client" />
	  <Protobuf Include="Protos\trading_pair.proto" GrpcServices="Client" />
	  <Protobuf Include="Protos\wallet.proto" GrpcServices="Client" />
	</ItemGroup>

</Project>
