<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>TradingPairService.Domain</RootNamespace>
		<AssemblyName>TradingPairService.Domain</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <Folder Include="Enums\" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="SharedLibrary">
	    <HintPath>..\..\References\SharedLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
