<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>AuthService.Application</RootNamespace>
		<AssemblyName>AuthService.Application</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AuthService.Domain\AuthService.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Commands\" />
	  <Folder Include="Interfaces\ExternalServices\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="SharedLibrary">
	    <HintPath>..\..\References\SharedLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
