syntax = "proto3";

option csharp_namespace = "MatchingEngineService.Api.Protos";

package matching_engine;

service MatchingEngineGrpc {
  rpc SubmitOrder (SubmitOrderRequest) returns (SubmitOrderResponse);
  rpc CancelOrder (CancelOrderRequest) returns (CancelOrderResponse);
  rpc GetOrderBook (GetOrderBookRequest) returns (GetOrderBookResponse);
}

enum OrderSideGrpc {
  ORDER_SIDE_UNSPECIFIED = 0;
  ORDER_SIDE_BUY = 1;
  ORDER_SIDE_SELL = 2;
}

enum OrderTypeGrpc {
  ORDER_TYPE_UNSPECIFIED = 0;
  ORDER_TYPE_MARKET = 1;
  ORDER_TYPE_LIMIT = 2;
}

message SubmitOrderRequest {
  string order_id = 1;
  string pair_symbol = 2;
  OrderSideGrpc side = 3;
  OrderTypeGrpc type = 4;
  string price = 5;
  string quantity = 6;
}

message SubmitOrderResponse {
  bool accepted = 1;
  string message = 2;
}

message CancelOrderRequest {
  string order_id = 1;
  string pair_symbol = 2;
}

message CancelOrderResponse {
  bool canceled = 1;
}

message GetOrderBookRequest {
  string pair_symbol = 1;
  int32 depth = 2;
}

message OrderBookLevelGrpc {
  string price = 1;
  string quantity = 2;
}

message GetOrderBookResponse {
  string pair_symbol = 1;
  repeated OrderBookLevelGrpc bids = 2;
  repeated OrderBookLevelGrpc asks = 3;
}
