syntax = "proto3";

option csharp_namespace = "TradingService.Infrastructure.Protos";

package trading_pair;

service TradingPairGrpc {
  rpc Ping (PingRequest) returns (PingResponse);
  rpc GetBySymbol (GetTradingPairRequest) returns (TradingPairGrpcResponse);
}

message PingRequest {
  string message = 1;
}

message PingResponse {
  string message = 1;
}

message GetTradingPairRequest {
  string symbol = 1;
}

message TradingPairGrpcResponse {
  bool found = 1;
  string symbol = 2;
  string base_asset = 3;
  string quote_asset = 4;
  string min_order_quantity = 5;
  string min_order_value = 6;
  int32 price_precision = 7;
  int32 quantity_precision = 8;
  bool is_active = 9;
}
