syntax = "proto3";

option csharp_namespace = "TradingService.Infrastructure.Protos";

package wallet;

service WalletGrpc {
  rpc LockFund (FundLockGrpcRequest) returns (FundLockGrpcResponse);
  rpc UnlockFund (FundLockGrpcRequest) returns (FundLockGrpcResponse);
  rpc GetOrCreateAsset (GetOrCreateAssetRequest) returns (AssetGrpcResponse);
  rpc SettleTrade (SettleTradeRequest) returns (SettleTradeResponse);
}

message FundLockGrpcRequest {
  string user_id = 1;
  string asset_id = 2;
  string amount = 3;
}

message FundLockGrpcResponse {
  string locked_balance = 1;
}

message GetOrCreateAssetRequest {
  string asset_name = 1;
}

message AssetGrpcResponse {
  string asset_id = 1;
  string asset_name = 2;
}

message SettleTradeRequest {
  string trade_id = 1;
  string buyer_user_id = 2;
  string seller_user_id = 3;
  string base_asset_id = 4;
  string quote_asset_id = 5;
  string quantity = 6;
  string price = 7;
}

message SettleTradeResponse {
  bool success = 1;
}
