<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>MarketDataService.Domain</RootNamespace>
		<AssemblyName>MarketDataService.Domain</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <Folder Include="Entities\" />
	  <Folder Include="Enums\" />
	</ItemGroup>

</Project>
