<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>WalletService.Application</RootNamespace>
		<AssemblyName>WalletService.Application</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WalletService.Domain\WalletService.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commands\" />
		<Folder Include="Interfaces\ExternalServices\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
		<PackageReference Include="Nethereum.HdWallet" Version="6.1.0" />
		<PackageReference Include="Nethereum.Web3" Version="6.1.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="SharedLibrary">
	    <HintPath>..\..\References\SharedLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
