<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>TradingService.Api</RootNamespace>
		<AssemblyName>TradingService.Api</AssemblyName>
		<UserSecretsId>836f3e46-84b7-4711-95f5-6509324dcc55</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\trading_pair.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
		<Folder Include="Extensions\" />
		<Folder Include="Middlewares\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TradingService.Application\TradingService.Application.csproj" />
		<ProjectReference Include="..\TradingService.Infrastructure\TradingService.Infrastructure.csproj" />
		<ProjectReference Include="..\TradingService.SqlMigration\TradingService.SqlMigration.csproj" />
	</ItemGroup>

</Project>
